### ISSUE TITLE
Error in Cordova Build Cannot Find Module XCODE

### ISSUE THREAD

**Issue by Drew-Hyatt** [bitpay/cordova-plugin-qrscanner#1]
I can't seem to get this plugin working by following the directions via the readme.  There seems to be an issue when readding platform ios in the CLI. Any idea please help. 

![screen shot 2016-02-12 at 4 51 41 pm](https://cloud.githubusercontent.com/assets/12660927/13022998/65bd3b52-d1aa-11e5-8940-c33ea6614a9b.png)

**Comment by bitjson** [comment]
Hi @Drew-Hyatt, thanks for opening the issue, it looks like I missed some documentation. The script which updates your project to support Swift requires the `xcode` node module, so you'll need to install it too: `npm install --save xcode`.

I just made [some clarifications to the documentation](https://github.com/bitpay/cordova-plugin-qrscanner/commit/bd46f26a37c109aed3f63fc313daf05a157bf0c2). Thanks!
