### ISSUE TITLE
No video preview showing (black screen)

### ISSUE THREAD

**Issue by RaiserWeb** [bitpay/cordova-plugin-qrscanner#100]
Hi,
I cannot get the video to show. It is loading correctly, and I am able to scan a qr code. But I cannot get the video preview to display. I have been through my DOM layers, and applied background:none transparent on all of them, but still no preview is shown.

Same issues as here: 
https://stackoverflow.com/questions/43907710/cordova-plugin-qrscanner-no-video-preview
https://stackoverflow.com/questions/43225506/cordova-cordova-plugin-qrscanner-opaque-camera-view

Any help would be appreciated.

**Comment by RaiserWeb** [comment]
Brief update - I had an android emulator running, at the same time as loading in the browser. When I shut the emulator down, the web cam browser view kicked in.
All I needed to do was then set my app div to have 0 opacity.

**Comment by blokeish** [comment]
You need to set the camera to be used by the emulator. This might help.. http://viralpatel.net/blogs/enable-camera-in-android-emulator/
