### ISSUE TITLE
error when running cordova build

### ISSUE THREAD

**Issue by mehdirazajaffri** [bitpay/cordova-plugin-qrscanner#104]
Element uses-feature#android.hardware.camera at AndroidManifest.xml:20:5-60 duplicated with element declared at AndroidManifest.xml

Element uses-permission#android.permission.CAMERA at AndroidManifest.xml:21:5-65 duplicated with element declared at AndroidManifest.xml

There are multiple entries in androidManifest.xml

<uses-permission android:name="android.permission.CAMERA" android:required="false" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-permission android:name="android.permission.CAMERA" />

**Comment by SidaouiBilel** [comment]
I got the same problem. I fixed it by using either the qr code scanner or the barcode scanner it seems like you can't use both.

**Comment by mehdirazajaffri** [comment]
i am only using qr-scanner

**Comment by Story5** [comment]
zbar also conflict with qrsanner，remove one of them if you use both
