### ISSUE TITLE
install from npm or cordova registry doesn't support windows 10

### ISSUE THREAD

**Issue by jabelcs** [bitpay/cordova-plugin-qrscanner#106]
Hello all.

I'm developing a cordova app and I would like to use this plugin has it seems to be the must rubost to read QR Codes.

I installed this plugin using: cordova plugin add cordova-plugin-qrscanner.
Building for windows gives me this error: "Unhandled exception at line 5, column 1 in ms-appx-web://pt.dietmed.vademecum/www/plugins/cordova-plugin-qrscanner/src/windows/lib/qrScanner.js
0x800a1391 - JavaScript runtime error: 'QRReader' is undefined";

On android doesn't do anything (not tested on ios yet);

After reading some issues on github I came across to one post mensioning Targets Windows 10 UWP, so I decided to compare the files from this repository with the ones downloaded via cordova install and I checked that they are totally diferent...

For example the QRReader.csproj downloaded from cordova targets "Project ToolsVersion="12.0"" and the QRReader.csproj file in this repository targets "Project ToolsVersion="14.0"" and this is just an example...

Is there a way for me to download the lattest versions from cordova registry?

Thanks in advance.

**Comment by jabelcs** [comment]
Sorry, this plugin works perfectly on android but giving the error on windows 10.

I´m using Visual Studio 2015 with Cordova.

**Comment by gabrielbazan7** [comment]
Hi.  This are the steps to make the scanner works: 

1. Install the plugin
2. cd plugins/cordova-plugin-qrscanner
4. remove this `^` from webpack dependency on package.json (bitpay/cordova-plugin-qrscanner#78) 
5. then run `npm i` inside `plugins/cordova-plugin-qrscanner ` folder
6. then `npm run build`
7. Go to root
8. rm -rf platforms/windows
9. cordova platform add windows

10. Add to cordova project index.html (platform/windows/www/index.html) file after `<script src="cordova.js"></script>` this:
`<script type="text/javascript" src="plugins/cordova-plugin-qrscanner/www/www.min.js"></script>`

11. Check windows 10 manifest file and add if it is missing:
<DeviceCapability Name="webcam" />

12. Open Visual Studio. Inside CordovaApp.windows10 you will find a references folder. Right click. Add references. Add QRReader. 

13. Run in your device with ARM target.

**Comment by bitjson** [comment]
Fixed in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) 🚀
