### ISSUE TITLE
Preview not working Android (Crosswalk) - Any Update?

### ISSUE THREAD

**Issue by theknown** [bitpay/cordova-plugin-qrscanner#107]
It all works fine on iOS. Perfect!

However, on Android (with crosswalk), the preview screen doesn't show.  I tried everything (in terms of making overlapping layers transparent). That is not the the problem.

Preview screen doesn't show.  When you hold a QR code in front of the camera though, it does throw the success event.  So apparently it is scanning for Android, but it doesn't display the camera screen.

I've read this issue is related to Crosswalk on Android?  Is there a fix? Will there be a fix?

Let me know.

**Comment by dcousens** [comment]
@theknown see how https://github.com/bitpay/cordova-plugin-qrscanner/pull/96 works for you... it isn't functionality.  But it can give you a working camera and preview.

**Comment by theknown** [comment]
I'm not sure if I understand that correctly, but I just replaced the 2 files with the new ones in that thread (#96):
- www.min.js
- QRScanner.java

Still the exact same issue on Android.. No camera preview.

**Comment by dcousens** [comment]
@theknown are you sure it re-compiled as required?  There are multiple copies made by cordova.

**Comment by theknown** [comment]
I just tested again on multiple android devices with the modified code that you mentioned (#96).

Android now opens the camera preview in the app. However, the preview is a black screen all the time.

Again, holding a QR code in front of the camera and it throws the success event. But instead of showing no camera preview on Android, it now shows a completely black camera preview.

Thoughts?

**Comment by dcousens** [comment]
@theknown apply https://github.com/dcousens/cordova-plugin-qrscanner/commit/be4376cda07ebfc1d412feec4807d62b16c85e81 - it was what I settled with.

**Comment by theknown** [comment]
Still not working for me. Could I hire you to take a look at it on teamviewer on my computer @dcousens 

I just sent you an email through your site.

**Comment by Nauzer** [comment]
I had the same issue.
It is because the z-order of Webview vs de Camera preview.
Adding the following helped to show preview on Android with Xwalk:

for config.xml (if regular Cordova project)
`<preference name="xwalkZOrderOnTop" value="false" />`

for meteor mobile-config.js (for meteor project)
`App.setPreference('xwalkZOrderOnTop', false);`

**Comment by bitjson** [comment]
It's been a while here, so I'm going to close this. If anyone is still having trouble, feel free to open a new issue.

**Comment by sJonatas** [comment]
@Nauzer solution worked fine for me!
TYSM!

**Comment by RobbertWolfs** [comment]
This works without xwalk.. but with xwalk enabled our preview is black.. 

scanning still works but no preview...

**Comment by zhang-teng-da** [comment]
I'm new for cordova ,but I think I've found a solution to this issue.
This plugin's camera preview works much like [cordova-plugin-googlemaps,](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/Installation/crosswalk/README.md)
add the following to config.xml
`<preference name="xwalkZOrderOnTop" value="true" />`
`<preference name="BackgroundColor" value="0" />`

my cordova-plugin-crosswalk-webview version is 2.4.0 

hope it helps
