### ISSUE TITLE
Plugin issue i can't scan 

### ISSUE THREAD

**Issue by anassfiqhi** [bitpay/cordova-plugin-qrscanner#110]
please i need help . I can't scan QRcode , the prepare method works but scan method dosen't work
this is my code i'm using onsen ui framework with angular

`  <script>
    ons.bootstrap()
      .controller('HelloController', function($scope) {
        $scope.world = 'World';
        $scope.scan = function() {
                  // For the best user experience, make sure the user is ready to give your app
                  // camera access before you show the prompt. On iOS, you only get one chance.

                  QRScanner.prepare(onDone); // show the prompt

                  function onDone(err, status){
                    if (err) {
                    // here we can handle errors and clean up any loose ends.
                    alert("prepare "+err);
                    }
                    if (status.authorized) {
                      // W00t, you have camera access and the scanner is initialized.
                      // QRscanner.show() should feel very fast.
                          alert("prepare "+status.authorized);
                    } else if (status.denied) {
                    // The video preview will remain black, and scanning is disabled. We can
                    // try to ask the user to change their mind, but we'll have to send them
                    // to their device settings with `QRScanner.openSettings()`.
                        alert("prepare "+status.denied);
                    } else {
                      // we didn't get permission, but we didn't get permanently denied. (On
                      // Android, a denial isn't permanent unless the user checks the "Don't
                      // ask again" box.) We can ask again at the next relevant opportunity.
                    }
                  }

                  // Start a scan. Scanning will continue until something is detected or
                  // `QRScanner.cancelScan()` is called.
                  QRScanner.scan(displayContents);

                  function displayContents(err, text){
                    if(err){
                      // an error occurred, or the scan was canceled (error code `6`)
                      alert("scan "+err);
                    } else {
                      // The scan completed, display the contents of the QR code:
                      alert("scan "+text);
                    }
                  }

                  // Make the webview transparent so the video preview is visible behind it.
                  QRScanner.show();
                  // Be sure to make any opaque HTML elements transparent here to avoid
                  // covering the video.

        };
      });
    ons.ready(function() {
      console.log("Onsen UI is ready!");
    });
  </script>`

`
<ons-page ng-controller="HelloController as hello">
    <ons-toolbar>
      <div class="center">Introduction</div>
    </ons-toolbar>

    <div class="content" style="margin: 10px;">
      <p ng-click="scan()">What is your name?</p>
      <p>
        <ons-input modifier="underbar" ng-model="hello.world" placeholder="Your name" float></ons-input>
      </p>
      <p>
        Hello, {{ hello.world || 'stranger' }}!
      </p>
    </div>
  </ons-page>
`

**Comment by anassfiqhi** [comment]
`
![html](https://user-images.githubusercontent.com/9436806/28741441-8fd189e2-7448-11e7-9d99-83cf6b7c95fa.png)
![js](https://user-images.githubusercontent.com/9436806/28741442-8fdc382e-7448-11e7-9d6a-1905c9e503cd.png)

`

**Comment by bitjson** [comment]
Fixed in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) 🚀
