### ISSUE TITLE
android:required only works for <uses-feature> not <uses-permission>

### ISSUE THREAD

**Issue by kongyim** [bitpay/cordova-plugin-qrscanner#111]
Please check plugin.xml line 23

the android:required field is useless, please remove it.
Manifest merger will fail with multiple errors

from
`<uses-permission android:name="android.permission.CAMERA" android:required="false" />`

to 
`<uses-permission android:name="android.permission.CAMERA" />`

Otherwise, if other plugin having android.permission.CAMERA permission will have merge conflict

**Comment by aramando** [comment]
Yes please remove this as it seems to be causing this plugin to not play nicely with others that also use the camera. I just had to remove and re-add my whole Android platform to stop duplicate entries being created in my AndroidManifest.xml and failing the build.

**Comment by bitjson** [comment]
Is this still an issue?

(Going to close for now, but please feel free to send a PR if something still needs to change.)

**Comment by CjoyHome** [comment]
This is still an issue

**Comment by CjoyHome** [comment]
![image](https://user-images.githubusercontent.com/26813427/44791096-77228400-abd3-11e8-9743-47f72ac872cd.png)
![Uploading image.png…]()

**Comment by jhgeluk** [comment]
Still experiencing this issue!

**Comment by zuzkadirova** [comment]
> Please check plugin.xml line 23
> 
> the android:required field is useless, please remove it.
> Manifest merger will fail with multiple errors
> 
> from
> `<uses-permission android:name="android.permission.CAMERA" android:required="false" />`
> 
> to
> `<uses-permission android:name="android.permission.CAMERA" />`
> 
> Otherwise, if other plugin having android.permission.CAMERA permission will have merge conflict

Wjejj3
