### ISSUE TITLE
Plugin not working on browser

### ISSUE THREAD

**Issue by vinicius-dev** [bitpay/cordova-plugin-qrscanner#112]
I'm trying a implementation on a pwa so its really necessary to work on the phone browser. It dont appear any errors on the console but the plugin dont seems to work. Any help?

**Comment by bitjson** [comment]
Fixed in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) 🚀
