### ISSUE TITLE
Providing a callback to show or hide leaves the background transparent

### ISSUE THREAD

**Issue by danielo515** [bitpay/cordova-plugin-qrscanner#113]
Hello,

First of all, thank you for this great plugin, works flawlessly most of the time. However I found one weird behavior: I was using `Qrscanner.show` and hide without problems, everything was working as expected: transparent background on show and the opposite on hide, leaving me the task of modifying the body of the HTML file . Then I decided to provide a callback to every method so I can register the status. To my surprise (and after a lot of troubleshooting) this leaves the background color of the HTML body with a transparent value within the style property of the Dom node. 

1. Prepare the scanner 
1. Show the scanner (with callback
callback) and made everything transparent with injected stylesheet, not adding them to the Dom node 
1. Hide the scanner. Them something adds a transparent style property to the HTML body 
1. The same happens with destroy 

Thanks and regards

**Comment by bitjson** [comment]
Fixed in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) 🚀
