### ISSUE TITLE
Problems with iOS platform when working on Android and browser

### ISSUE THREAD

**Issue by MackEdweise** [bitpay/cordova-plugin-qrscanner#126]
I have used this plugin to create a relatively simple QR scanner application that works perfectly on Android and in the browser. However, I have found that on iOS the plugin did not initialize. The QRScanner object was attached to the window but any calls to its functions, including QRScanner.prepare(), QRScanner.getStatus(), QRScanner.openSettings(), etc. all returned undefined and did nothing. The project built and ran on my iPad with no errors. 

Upon further investigation I found that xcode did report some problems during the build process, specifically: `Plugin 'QRScanner' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.`

I confirmed that `<plugin name="cordova-plugin-qrscanner" spec="2.5.0" />` was present in config.xml and that the version of the plugin was in fact 2.5.0.

I also found that updating my project's html files was not reflected in each new build. This made me suspicious of the integrity of my ios project. So, I ran `ionic cordova rm ios` followed by `ionic cordova add ios`. Following this, I have observed that the project does not build successfully but reveals some more specific problems with the plugin's incompatibility. Specifically, the file QRScanner.swift file has 16 problems: 

![screen shot 2017-10-28 at 8 09 23 pm](https://user-images.githubusercontent.com/10645577/32139609-032b2324-bc1c-11e7-9c8f-33889cbadfea.png)

I have attempted to change the SWIFT_VERSION to each of 1.0, 2.0, 3.0 and 4.0 and this has resulted in a few changes in the errors that are reported, but nothing works. I also tried to use the tool to update the code to the latest version of swift but this reported that there were no incompatibilities.

**Comment by isstoyanov** [comment]
You need to update XCode to latest version

**Comment by bitjson** [comment]
Fixed in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) 🚀
