### ISSUE TITLE
How to display QR Scanner Box overlay?

### ISSUE THREAD

**Issue by Huiting-Yeong** [bitpay/cordova-plugin-qrscanner#130]
I am able to successfully scan a QR code. 

Would like to ask is there a feature to automatically display the QR scanner box overlay so users know where to focus there camera at? 

Similar to the example screenshots at the readme.md page.

**Comment by felix9607** [comment]
Thats something i'd like to have too and I think it's nothing else then a transparent Background but I didn't really put enough effort into it to figure it out.

**Comment by Huiting-Yeong** [comment]
Does anybody know what is the ideal size restriction of the overlay box?

**Comment by leftdead7** [comment]
you ca use html to display a box overlay, However it will be just for show , the plugin may read the qr even if its not placed inside your box completely.
![1513605704347](https://user-images.githubusercontent.com/23002003/34109601-233a5104-e42a-11e7-9cd7-242b9ae7f4ad.JPEG)

**Comment by bitjson** [comment]
This is something you should do in the CSS of your app. See https://github.com/bitpay/copay for an example.

**Comment by rodrigograca31** [comment]
@bitjson seems they are using `@zxing/ngx-scanner` .... not this plugin directly....
I also have no idea of the area this plugin uses to detect the QR.
Its not the entire camera stream right? its only the middle but not sure what size it is to then make something in CSS/HTML

**Comment by Simone4e** [comment]
Is there no way to directly integrate an overlay option?
