### ISSUE TITLE
The plugin convert all letters to upper case letters

### ISSUE THREAD

**Issue by sherif-hfm** [bitpay/cordova-plugin-qrscanner#136]
The plugin convert all scanned letters to upper case letters

**Comment by bitjson** [comment]
Hmm.. I'd be willing to bet that what you're seeing is the result of scanning a QR code encoded in [Alphanumeric mode](https://en.wikipedia.org/wiki/QR_code#Encoding). It's not that the plugin is converting to uppercase, it's that the code itself doesn't include capitalization information. 

I can confirm that properly encoded QR codes are displaying the proper capitalization, so I think it's safe to close this issue. Please feel free to reopen if that doesn't explain the issue.
