### ISSUE TITLE
Compile errors in xcode 9.2

### ISSUE THREAD

**Issue by heartfelttech** [bitpay/cordova-plugin-qrscanner#143]
xcode complains that the ios support is in swift2 and should be in swift3. It also says that conversion would require an older version of xcode.

Installed via `cordova plugin add cordova-plugin-qrscanner`

**Comment by stevenwaskey** [comment]
You need XCode 8.* to convert Swift 2 -> Swift 3.  You can download XCode 8.3.3 which will run side-by-side w/ XCode 9 without issue.  You'll need your Apple Developer account as it's a secured asset.

[XCode 8.3.3](https://developer.apple.com/services-account/download?path=%2FDeveloper_Tools%2FXcode_8%2FXcode_8.xip)

**Comment by bitjson** [comment]
Fixed in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) 🚀
