### ISSUE TITLE
Install fails with Error: Cannot find module '../cordova/platform_metadata'

### ISSUE THREAD

**Issue by jmargolese** [bitpay/cordova-plugin-qrscanner#144]
Installing on Ionic results in a failure with:

> Saved plugin info for "cordova-plugin-qrscanner" to config.xml
> 
> (node:2518) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../cordova/platform_metadata'

There were [similar errors](https://forum.ionicframework.com/t/ionic-build-fails-with-error-cannot-find-module-cordova-platform-metadata/116108/10) with cordova-plugin-ios etc that are supposed to have been fixed and may show the error.

Workaround is to downgrade from Cordova 8 to cordova 7.1.0  
  npm uninstall -g cordova
 npm install -g cordova@7.1.0
 
 and then installed with cordova...  not ionic cordova.
 
 
 My env when I first encountered the error:

ionic info

cli packages: (/Users/joelm/.nvm/versions/node/v8.4.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v8.4.0
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : /Users/joelm/Library/Android/SDK

Misc:

    backend : pro

**Comment by peratik** [comment]
same issue please help

**Comment by adil-haddaoui** [comment]
Same issue here !!

**Comment by iCodr8** [comment]
Same Problem :(

**Comment by EnggZahidulislam** [comment]
Step 1: delete all folder except src and resources
Step 2: run command  npm install
Step 3: run command ionic serve
Step 4: run command ionic cordova build android
this process solved my issue

**Comment by iCodr8** [comment]
I couldn't fix it and now I'm using the [Barcode Scanner](https://ionicframework.com/docs/native/barcode-scanner/). This plugin can also scan QR codes.

**Comment by MarcelOerlemans** [comment]
I have the same error, and I do not use ionic.
Command:
phonegap plugin add cordova-plugin-qrscanner
Error:
(node:14296) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../cordova/platform_metadata'

Is there a fix or workaround available?

**Comment by yunderboy** [comment]
I've been encountering that same issue...

**Comment by MarcelOerlemans** [comment]
My solution: use phonegap-plugin-barcodescanner. Although I understand that might not be possible for everyone.

**Comment by pverdu** [comment]
> My solution: use phonegap-plugin-barcodescanner. Although I understand that might not be possible for everyone.

I wanted to try this plugin, since the phonegap-plugin-barcodescanner plugin is a bit slow in opening the scanner.

**Comment by MarcelOerlemans** [comment]
Yes, the phonegap scanner is definately a bit slower. But what can one do :(

**Comment by pverdu** [comment]
Yeah indeed. I had implemented Scandit which is superior over all scanners, but it's way to expensive also.

**Comment by matiu** [comment]
As a workaround, you can downgrade to cordova 7:
 ` npm uninstall -g cordova && npm install -g cordova@7.1.0`

**Comment by Story5** [comment]
I have the same issue

**Comment by pverdu** [comment]
> I have the same issue

I got it to work eventually.
I just kept removing the platforms and node_modules. Added the platforms and did an npm install again.
I think i also added "cordova-plugin-add-swift-support" to package.json with version number "^1.7.2".

**Comment by wasinr** [comment]
try this 

This was a bug in cordova-plugin-add-swift-support, just update it to latest version (1.7.1)

cordova plugin rm cordova-plugin-add-swift-support --force
cordova plugin add cordova-plugin-add-swift-support

credit : [https://stackoverflow.com/questions/48087357/cordova-8-ios-4-5-4-cannot-find-module-cordova-platform-metadata](https://stackoverflow.com/questions/48087357/cordova-8-ios-4-5-4-cannot-find-module-cordova-platform-metadata)

**Comment by bitjson** [comment]
Fixed in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) 🚀
