### ISSUE TITLE
Can't build for ios in phonegap

### ISSUE THREAD

**Issue by idclev31** [bitpay/cordova-plugin-qrscanner#149]
Hello!
I use phonegap for build my app.
I have sucessfull build for android (everything works fine)
But, i can't build for ios.
It say's 'Error code 65 for command: xcodebuild'
Is there some way to fix this?
Thank you.

**Comment by peratik** [comment]
same issue please help

**Comment by LucyLucyy97** [comment]
You can only build for iOS on a Mac, and you need to have Xcode installed

**Comment by stevenwaskey** [comment]
`man sysexits`

See (65)
```
EX_DATAERR (65)
The input data was incorrect in some way.  This should only be used for user's data and not system files.
```

While I'm sure it's not always the case, in my experience, Error Code 65 has been related to Code Signing issues.

**Comment by peratik** [comment]
> You can only build for iOS on a Mac, and you need to have Xcode installed

Error on build on a Mac with Xcode installed.

**Comment by bitjson** [comment]
2.6.0 was just released – if you're still having issues, please open a new issue with detailed steps to reproduce. Thanks!
