### ISSUE TITLE
Why cant we use the scanner preview in a div that we decided?

### ISSUE THREAD

**Issue by OzcanI** [bitpay/cordova-plugin-qrscanner#150]
How can I use my scanner preview in a div or dom element instead of dealing with transparenting some backgrounds?

**Comment by andreagobetti** [comment]
Long story short: you can't.
You should use css to hide everything it's over the camera image, I think they chose this method because dealing with the effective size of the div would be a real pain to implement

**Comment by bitjson** [comment]
👍 Exactly what @andreagobetti describes. It's much, much easier to manage your UI in CSS then trying to play games with the interface between the native and web layers.
