### ISSUE TITLE
plugin_not_installed - Android

### ISSUE THREAD

**Issue by makah** [bitpay/cordova-plugin-qrscanner#157]
I receive 'plugin_not_installed' when I try to `prepare()` in a blank Ionic (Version 3.20) project. Do I need to initialize qrScanner?

(using Ionic Pro View - Android device)

```
test() {
    this.qrScanner.prepare()
      .then((status: QRScannerStatus) => {        
          let scanSub = this.qrScanner.scan().subscribe((text: string) => {
            alert(text);
            this.qrScanner.hide();
            scanSub.unsubscribe();
          });          
          //......
      })
      .catch((e: any) => {
        alert('Error: ' + e);
      });
  }
```

**Comment by monichols** [comment]
plugin not installed means the plugin is not installed on your platform/device. Here are some things to try:

 1.Check your config.xml and make sure you see it there then your package.json try also removing and re-adding the platform (ionic cordova platform remove android ionic cordova platform add android). 
2. Then try a fresh install of the plugin. If it says that it is already installed I'd run ionic cordova plugin rm then ionic cordova plugin add. 

3.Please note that you should also be using a real device to test anything involving a plugin. If you're using the ionic dev app, don't test plugin functionality as it is not installing any packages to the device. Instead try ionic cordova run (iOS or android) with device tethered to computer or ionic cordova build (iOS or android) and install the file to your device.

Hope this helps,
Mo
