### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by allanpoppe** [bitpay/cordova-plugin-qrscanner#158]
Has this plugin been discontinued? The last update was almost two years ago.

Althought it's working (and it works very well, faster than others), it needs to be updated with new Cordova releases. Also, it's using cordova-plugin-swift-support, not cordova-plugin-**add**-swift-support, that's not being updated as the last one.

This is why some people are getting the `Cannot find module '../cordova/platform_metadata'` error.

**Comment by StarStep** [comment]
@allanpoppe how did you solve? I'm using it too...but unfortunately I'm not that good with cordova system yet. Thanks!

**Comment by allanpoppe** [comment]
@StarStep I changed the plug-in to use cordova-plugin-add-swift-support instead of cordova-plugin-swift-support. See [my fork](https://github.com/allanpoppe/cordova-plugin-qrscanner).

**Comment by bitjson** [comment]
updated in https://github.com/bitpay/cordova-plugin-qrscanner/releases/tag/2.6.0
