### ISSUE TITLE
How to select QR code image from gallery?

### ISSUE THREAD

**Issue by thisIsChetan** [bitpay/cordova-plugin-qrscanner#160]
Hi,

I am able to scan the qr code by live video feed by following the readme file. Just want to know how to read qr code from gallery.

**Comment by bitjson** [comment]
This is currently not supported, but you could use another plugin to get the image into JS land, then provide that image to the same function this library uses to read from the camera. PRs welcome!

**Comment by FourLeafClover** [comment]
@bitjson  if i use camera.getPicture get the picture(base64) from my gallery。how can i scan the picture by using base64 data.

**Comment by dodomui** [comment]
@FourLeafClover Did you manage to parse image to scan?
I can solved this by using another JS QR code decoder library qrcode-decoder-js.
But it happens that some QR code cannot be decode properly but this cordova-plugin-qrscanner never failed to decode any QR code yet.

Therefore, I hope can use this library to decode QR code image as well...
