### ISSUE TITLE
Center Decode Point is a little downward shift。

### ISSUE THREAD

**Issue by HanSunyi** [bitpay/cordova-plugin-qrscanner#161]
the smaller rect is the area where i can decode my QR code，but i want to make this area a little higher.
But i can't find a API to do this.    : ) 

eg.       ↓  
![1526451576 1](https://user-images.githubusercontent.com/16067355/40099820-4424270a-5914-11e8-845b-81d284a8c313.jpg)

blow picture is what i want ! 
![1526451710 1](https://user-images.githubusercontent.com/16067355/40099889-81e34dbe-5914-11e8-8a9a-991b07864acb.jpg)

**Comment by bitjson** [comment]
As far as I know, the QR scanner works on the entire view constantly. You shouldn't need to modify anything to read from any part of the view. Closing this for now, but please comment here if you're seeing something else.
