### ISSUE TITLE
'AVLayerVideoGravityResizeAspectFill' was obsoleted in Swift 4

### ISSUE THREAD

**Issue by cmartin81** [bitpay/cordova-plugin-qrscanner#166]
I just updated to latest Cordova (8.0.0) and the latest cordova-plugin-qrscanner (2.6.0)

When I try to build the project I get the following error:
AVFoundation.AVCaptureTorchMode:3:18: note: 'AVCaptureTorchMode' was obsoleted in Swift 4

Does anyone else get the same error?

**Comment by bitjson** [comment]
It sounds like your project is using Swift 4, while this plugin requires Swift 3. Are you using another plugin which requires Swift 4?

**Comment by cmartin81** [comment]
It is actually your plugin which installs swift 4
    
    Installing "cordova-plugin-qrscanner" for android

    Android Studio project detected

    Subproject Path: CordovaLib
    Subproject Path: app
    Installing "cordova-plugin-qrscanner" for ios

    Installing "cordova-plugin-add-swift-support" for ios

    Adding cordova-plugin-qrscanner to package.json

    Saved plugin info for "cordova-plugin-qrscanner" to config.xml

    Update IOS build setting SWIFT_OBJC_BRIDGING_HEADER to: "$(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h" for build configuration Debug
    Update IOS build setting SWIFT_OBJC_BRIDGING_HEADER to: "$(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h" for build configuration Release
    Update IOS build setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to: YES for build configuration Debug
    Use Swift language version 4
    Update IOS build setting SWIFT_OPTIMIZATION_LEVEL to: -Onone for build configuration Debug
    Update IOS build setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to: YES for build configuration Release
    Use Swift language version 4

**Comment by cmartin81** [comment]
It is now working as expected. It started working after deleting the plugin and platform directory. I also had to remove the line which referred to using swift 4 in config.xml

**Comment by danish1023** [comment]
QRScanner is causing error(swift support) on pgb. I have heard something like "bridging header". Can author please change your plugin code, so that it can work on pgb also. Desperately needed that. Please. Or guide me any workaround.

**Comment by dolosplus** [comment]
Has anyone find a workaround for this plugin? Swift 3 is no longer supported in XCode. I only can use Swift 4 or greater and that's causing a lot of errors from Swift Compiler.
For example, one of the errors stating:

`/AVFoundation.AVLayerVideoGravityResizeAspectFill:3:12: 'AVLayerVideoGravityResizeAspectFill' was obsoleted in Swift 3`
