### ISSUE TITLE
Implementation method for Ionic V1 apps

### ISSUE THREAD

**Issue by xcarlo31** [bitpay/cordova-plugin-qrscanner#184]
Is there a tutorial or a readme file for the implementation of this plugin in ionic v1? I spent the whole day looking at your guides and I think my problem is implementing the plugin on an ionic v1 app.

Thank you!

**Comment by xcarlo31** [comment]
I have successfully implemented the plugin.

**Comment by aurasoftrw** [comment]
@xcarlo31 could you please share your solution. i have tried everything with no success. the plugin works but i'm having trouble with the webview showing the preview

**Comment by xcarlo31** [comment]
Hi @aurasoftrw, I suggest you use the latest ionic which is ionic 4, there all the plugins are supported and all the problems encountered in Ionic 1 are already fixed.

**Comment by aurasoftrw** [comment]
@xcarlo31 thanks for your prompt response. so does this mean your solution was just updating your project to ionic 4?

**Comment by xcarlo31** [comment]
Nope, I found a way to implement the plugin and work it on our project.
I think I used this one for the ionic v1 project: https://github.com/phonegap/phonegap-plugin-barcodescanner
Can u elaborate your issue with the scanner?
