### ISSUE TITLE
Swift 5 issue

### ISSUE THREAD

**Issue by raghavdm** [bitpay/cordova-plugin-qrscanner#240]
As I am using Xcode 10.2, I want to upgrade this plugin to 3.0.0.
At time installing this plugin through cordova it is taking 2.6.0 version

When this plugin be available in 3.0.0

**Comment by renatolaurino** [comment]
The same here

XCODE 10.1

**Plugins/cordova-plugin-qrscanner/QRScanner.swift:38:42: Type 'AVLayerVideoGravity' (aka 'NSString') has no member 'resizeAspectFill'**

`Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 6.5.0
   Cordova Platforms     : android 7.1.4, ios 4.3.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 13 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61`

**Comment by cmgustavo** [comment]
Version 3.0.1 is available right now. https://www.npmjs.com/package/cordova-plugin-qrscanner

Thanks.

**Comment by Razorholt** [comment]
Well, no luck with PGB (PhoneGap Build) for iOS. I tried everything for hours - or days I should say. I don't even know if PGB is ready for Swift5 anyway. But thank you all for getting that plugin a boost!

**Comment by sonicwong** [comment]
tested v3.0.1 working with ionic v4.0.0 release which cordova-ios is 4.5.5.
