### ISSUE TITLE
IOS 12.2 BUG

### ISSUE THREAD

**Issue by MicroLord** [bitpay/cordova-plugin-qrscanner#245]
**When ios 12.1 is upgraded to 12.2 ,  you cannot see the qr code in the camera , but you can realize the code scanning function . Please help me ,  it is very urgent!**

**_Both version 2.6.0 and 3.0.1 were tried_**

![image](https://user-images.githubusercontent.com/10664096/55867161-88ddf800-5bb4-11e9-83bf-50a2fea80730.png)

**Comment by MicroLord** [comment]
Solved:
`<ion-app style="background: none transparent;"> </ion-app>`
thanks .

**Comment by Lyfei** [comment]
> Solved:
> `<ion-app style="background: none transparent;"> </ion-app>`
> thanks .

Not work for me.
I'm solved:
```
ionViewDidEnter() {
  this.changeCameraView(true)
}

ionViewWillLeave() {
  this.changeCameraView(false)
}

changeCameraView(isAdd: boolean) {
  const cameraView = 'cameraView'
  const element = window.document.querySelector('ion-app')
  console.log('element.classList before change: ' + element.classList)
// element.classList before change: ios ion-page hydrated
  if (isAdd) {
  element.classList.add(cameraView)
  } else {
  element.classList.remove(cameraView)
  }
  console.log('element.classList after change: ' + element.classList)
// element.classList before change: ios ion-page hydrated cameraView
}
```
the truth of cameraView:
```
ion-app.cameraView, ion-app.cameraView .nav-decor, ion-app.cameraView ion-content {
--background: #0000 none!important;
}
```
