### ISSUE TITLE
Android: black screen on app minimize and re-open

### ISSUE THREAD

**Issue by hottom** [bitpay/cordova-plugin-qrscanner#25]
if first enter app,it is ok. 
when click android return,then start app again,the screen is black.
If clear memory and restart app,it is ok.

**Comment by bitjson** [comment]
Happy to help. Could you put a test app on github so I can reproduce the issue?

**Comment by hottom** [comment]
Hi,
I have push test app on github.

https://github.com/hottom/scantest <https://github.com/hottom/scantest>

Please help me .
Thanks.


hottom

**Comment by bitjson** [comment]
Hey @hottom – I'm trying to reproduce this – could you describe a little more about what you're doing, and what you expect the plugin to do?

I think the default background for an Android app is black, so if your webview has no background, and the plugin is not showing a video preview, the background is expected to be black. Would you expect a different behavior?

**Comment by tobiasviehweger** [comment]
@bitjson @hottom I can reproduce this in our app. I can look into it!
