### ISSUE TITLE
Swift3 + viewfinder implementation

### ISSUE THREAD

**Issue by elledienne** [bitpay/cordova-plugin-qrscanner#27]
I forked the project and I converted it to Swift3 (it was quite easy to be honest), I also added a feature that adds a viewfinder during the scanning (a very simple square around the detected code).

Would you be interested in a PR?

**Comment by bitjson** [comment]
Hey @elledienne – we'd love for you to contribute! For compatibility across platforms (and API simplicity) we have avoided implementing any native viewfinder-type functionality, but we'd love to take a pull request with any refactoring needed for Swift 3.

**Comment by bitjson** [comment]
Hey @elledienne – I'm reviewing issues here this weekend, and I'd love to pull in your work. Would you still be willing to send in those changes for Swift 3?

**Comment by elledienne** [comment]
Hey @bitjson, so sorry for the late answer! I'll open a PR asap!

**Comment by bitjson** [comment]
Thanks for your work @elledienne! Included via https://github.com/bitpay/cordova-plugin-qrscanner/pull/38.
