### ISSUE TITLE
let the user define the the video tag where and how he wants it

### ISSUE THREAD

**Issue by mehdy** [bitpay/cordova-plugin-qrscanner#28]
I think it's bad that the video tag is created by lib itself and always appended to body.
I suggest that we let the user define a video tag however he wants and wherever in the DOM and if he didn't we'll do what we do now

**Comment by bitjson** [comment]
> I think it's bad that the video tag is created by lib itself and always appended to body.

Hey @mehdy – which platform implementation are you looking at? For iOS and Android, we don't use a `<video>` element at all (in fact on iOS, that isn't possible without allowing the video to take the full screen). The `cordova-browser` implementation is also designed to work as closely to the other platforms as possible.

**Comment by mehdy** [comment]
hmmm, yeah it makes sense. so I'll close the issue. thanks
