### ISSUE TITLE
Not working cordova-plugin-qrscanner

### ISSUE THREAD

**Issue by subhash8108** [bitpay/cordova-plugin-qrscanner#29]
Hello,

I have onesignal-cordova-plugin plugin installed on my cordova android app, when install your plugin after then run cordova project that time getting gradlew error.. if remove the onesignal-cordova-plugin then proper working. I like your package but not working for android

I think conflict file of plugin.

Please give me a suggestion.

![gradle error](https://cloud.githubusercontent.com/assets/542535/18860696/44b99e40-849d-11e6-9202-26a74ad13ee6.png)

**Comment by tobiasviehweger** [comment]
@bitjson This should be fixed by #26.
@subhash8108 Could you try installing by doing `cordova plugin install https://github.com/bitpay/cordova-plugin-qrscanner#70a931614765d69f01303654060779628dab5115`

**Comment by subhash8108** [comment]
How to remove "unnecessary dependency (breaks other plugins) ".?

**Comment by tobiasviehweger** [comment]
Just install the newest version of the plugin, directly from this repository.
Like I said, to test if it works, first uninstall the npm version:
`cordova plugin remove cordova-plugin-qrscanner`

Then (install master branch)
`cordova plugin install https://github.com/bitpay/cordova-plugin-qrscanner`

**Comment by bitjson** [comment]
Thanks for contributing the fix @tobiasviehweger! This was just released in version [2.3.1](https://github.com/bitpay/cordova-plugin-qrscanner/releases/tag/2.3.1).
