### ISSUE TITLE
status is null

### ISSUE THREAD

**Issue by feidianbo** [bitpay/cordova-plugin-qrscanner#3]
// Make sure the user will give your app camera access when prompted, then:
QRScanner.prepare(onDone); // prompt for access

function onDone(**status**){

status is null !!!!!!!!!!!?
and there is nothing when calling qrscan

  if (!status.authorized) {
    // the video preview will remain black, and scanning is disabled
    // you can try asking the user again, but you'll have to use `QRScanner.openSettings()`.
  }
}

// later in your app:

QRScanner.show(); // optional: make the webview transparent so the video preview is visible behind it

QRScanner.scan(displayContents); // scan until something is found

function displayContents(text){
  alert(text);
}

**Comment by bitjson** [comment]
What device and operating system version are you on? Can you provide any more sample code and debugging information?

**Comment by feidianbo** [comment]
@bitjson iPhone 6Plus / iOS 9.3

**Comment by bitjson** [comment]
Odd. Could you try running tests on your device?

**Comment by bitjson** [comment]
Hey @feidianbo – did you get a chance to try the tests? 

Also, are you using WKWebView with the plugin? This may be related to: https://github.com/bitpay/cordova-plugin-qrscanner/issues/4

**Comment by bitjson** [comment]
Other issue solved. Leaving this open for now – if you're still experiencing the issue, could you provide steps to reproduce?

**Comment by bitjson** [comment]
Closing for now – please let me know if this issue re-appears.
