### ISSUE TITLE
destroy on ios crashes

### ISSUE THREAD

**Issue by mattijswilms** [bitpay/cordova-plugin-qrscanner#33]
Hi,

When I use QRscanner on Cordova IOS it crashes on the line 330 (self.captureVideoPreviewLayer!.removeFromSuperlater()

when I call destroy.

**Comment by mattijswilms** [comment]
The whole app specifically crashes when you start using the qrscanner again.

**Comment by bitjson** [comment]
Hey @mattijswilms thanks for reporting the issue – I haven't been able to reproduce it yet. Could you possibly provide a code snippet that triggers the bug?

I'll be trying to fix this and two other iOS bugs in the next few days.

**Comment by bitjson** [comment]
Hey @mattijswilms, I'm trying to look into this issue today. Do you have any more information on how I can reproduce the bug or the error it generates? Did you see the error in the javascript console? Or were you debugging with Xcode?

**Comment by mattijswilms** [comment]
Hi Jason,

I was debugging with xcode. I don't have that much to go on but the destroy
command seems to cause the crash.

So I get a crash breakpoint in xcode, but the app crashes when I call the
prepare command again to scan for a second time.


2016-10-01 22:32 GMT+02:00 Jason Dreyzehner <notifications@github.com>:

**Comment by bitjson** [comment]
Thanks for the reply! When you get a chance, could you try to copy/paste the javascript that causes the bug? Or just a list of the steps you can go through to reliably reproduce the issue?

I've tried something like:
- prepare
- show
- scan
(messed with light, camera reversal, etc.)
- destroy
- prepare
- scan
- destroy
- prepare
- scan

And I'm not seeing any issues yet.

If you're willing, it would be great if you could clone this repo and run:
```
npm install
npm run gen-tests
npm run test:ios
```

That will produce a "Cordova Test Framework" testing app with simple buttons for manually testing functionality. If you can find a way to reproduce it there, I can dig into the issue more.

**Comment by bitjson** [comment]
Hey @mattijswilms – have you had any luck confirming a method of reproducing this issue?
