### ISSUE TITLE
Can't compile Android app when targeting SDK version 31

### ISSUE THREAD

**Issue by dpalou** [bitpay/cordova-plugin-qrscanner#383]
The following error appears in console when I try to compile for Android using android-targetSdkVersion 31:

> Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

This seems to be caused by the zxing-android-embedded library, see this issue: https://github.com/journeyapps/zxing-android-embedded/issues/718

I tried to fix this using edit-config in my config.xml file, but since this <activity> is declared in a gradle dependency the edit-config is unable to find it.

Now Google Play requires apps to target SDK version 31, so this means we cannot publish our apps until this issue is fixed.

Has anyone found any workaround?

**Comment by dpalou** [comment]
After further research I think the issue wasn't caused by this plugin, I think it was caused by phonegap-plugin-push so I'm closing this one, sorry for the noise.

**Comment by sushibear** [comment]
I have the same problem. After deleting this plugin, building my App was no problem.
