### ISSUE TITLE
Optimize scanning on Android

### ISSUE THREAD

**Issue by bitjson** [bitpay/cordova-plugin-qrscanner#39]
Can we optimize scanning performance on Android by customizing some options from https://github.com/journeyapps/zxing-android-embedded? We only need to scan QR codes – I think the implementation is wasting a lot of cycles on other formats.

**Comment by tobiasviehweger** [comment]
Is it thoug? I think we are limiting this to QR-Codes in this line: https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/src/android/QRScanner.java#L458

**Comment by bitjson** [comment]
I had totally missed this before (and quickly added this issue from memory). Thanks @tobiasviehweger, the Android platform is fantastic!

**Comment by tobiasviehweger** [comment]
@bitjson No worries :)
