### ISSUE TITLE
Build failed in IOS

### ISSUE THREAD

**Issue by BenLaKnet** [bitpay/cordova-plugin-qrscanner#396]
Hi,

I try this plugin to develop for android, all is running and now when I would like to run in iOS I have error messages when building app.
what's wrong ?

cordova: 11
cordova-ios: 6.2.0

How to install nosoloforks fork ?

**Comment by BenLaKnet** [comment]
Help needed...

**Comment by KKDestiny** [comment]
can try this: find the file "QRScanner.swift", then change all "UIApplication.openSettingsURLString" to "UIApplicationOpenSettingsURLString"

**Comment by BenLaKnet** [comment]
@KKDestiny many thanks.
