### ISSUE TITLE
iPhone 14 Can't focus 

### ISSUE THREAD

**Issue by Attendwise** [bitpay/cordova-plugin-qrscanner#400]
Hi. have scan problems on iPhone 14. Ios 16.2
can't focus om QR code. i seames like the autofocus i not working

Works fantastic on other iPhones

**Comment by pawelszewczak** [comment]
@Attendwise I have the same problem on iPhone 15, did you somehow solve this problem?

**Comment by Attendwise** [comment]
Yes, updated to latest Cordova QR code reader

cordova plugin add cordova-plugin-qrscanner-11
