### ISSUE TITLE
White background in front of view

### ISSUE THREAD

**Issue by daankrs** [bitpay/cordova-plugin-qrscanner#44]
I can't get this app to work. There seems to be always a white screen in front of the camera view.

Even when I cloned the test repository (qrscanner-test) there was a white screen in front. You could tell the plugin was working because it would scan, and when you swiped down you could see the top of the camera view because you basically swiped the whole app down. 
When calling the Hide function, there was only white when you swiped down, but after calling show again, you could see parts of the view on top or bottom when swiping. 

I'm pretty sure I'm not forgetting an html layer because it shows the same behaviour in the test repository, and according to the status thingie everything seems to be working fine too.
I'm using iOS 10.0.1 and the latest version of Phonegap (6.3.3) and XCode (8.0).

I hope you have a clue of what's going on because I don't 😞 

{"authorized":true,"denied":false,"restricted":false,"prepared":true,"scanning":true,"previewing":true,"showing":true,"lightEnabled":false,"canOpenSettings":true,"canEnableLight":true,"canChangeCamera":true,"currentCamera":0}

**Comment by bitjson** [comment]
Hey @daankrs – you're looking at this project, right? https://github.com/bitjson/qrscanner-test

Could you post an issue there? Please include a screenshot/video if possible!

**Comment by daankrs** [comment]
Hi, sorry. I thought it belonged here because I only used that project to confirm it wasn't a problem in my own app. In my own app, in which I use this repository, the same behavior shows. Here is a little video to show the problem:
https://youtu.be/H6ZiVK4mDUA
