### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by murrekatt** [bitpay/cordova-plugin-qrscanner#45]
What's the license of this plugin? MIT?

**Comment by bitjson** [comment]
Hey @murrekatt the license is MIT – you can find it defined in [package.json](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/package.json#L48). It was also added during the [initial release](https://github.com/bitpay/cordova-plugin-qrscanner/commit/fbdca00967b817ae4edc572881e15cddf53c3ec8), so there shouldn't be any ambiguity. 🚀

**Comment by murrekatt** [comment]
Maybe add a license file?

**Comment by bitjson** [comment]
@murrekatt – good idea, pull request opened: #46
