### ISSUE TITLE
Crosswalk support

### ISSUE THREAD

**Issue by dPary** [bitpay/cordova-plugin-qrscanner#47]
I create a new project to test this plugin,and it work fine.But when i add crosswalk in my project,it shown a blank screen,and go back previous page,the screen flashed.

**Comment by dcousens** [comment]
@dPary did you end up resolving this?

**Comment by bitjson** [comment]
I've not tested the plugin with crosswalk – I'm fairly sure it would require some development to get working.

You may want to consider not using crosswalk though – the Android ecosystem has come a long way in the past few years, and there are relatively few devices still in use which lack the Chrome browser webview (Android 4.4+). 

Unless you specifically need to support those devices, you'll either be spending a lot of effort either maintaining separate builds, or you'll be adding a very bulky dependency to your download for all users.

**Comment by dPary** [comment]
@dcousens not yet...

**Comment by dPary** [comment]
@bitjson Thanks for replying

**Comment by dcousens** [comment]
@bitjson the concern is that a lot of devices do not have a consistent web view, and will have things as simple as `UInt8Array` have sporadic support.

Not to mention UI problems with inconsistent support for things like flex-box etc.

Crosswalk solves those issues in a way you can trust the crypto isn't silently failing.

**Comment by dcousens** [comment]
For the record, it works great using https://github.com/apache/cordova-plugin-wkwebview-engine

**Comment by gildebrand** [comment]
Has anyone been able to resolve this? Would very much like to be able to use this plugin together with Crosswalk on Android, and would happily look deeper into implementing it in this plugin if I only knew where to start!

**Comment by dcousens** [comment]
I think I've resolved it, will submit a PR ASAP.

**Comment by Nauzer** [comment]
If you are experiencing problems with Xwalk - especially showing preview you need to adjust your config.xml.

for config.xml (if regular Cordova project)
<preference name="CrosswalkAnimatable" value="true" />

for meteor mobile-config.js (for meteor project)
App.setPreference('CrosswalkAnimatable', true);

**Comment by felixbroehl** [comment]
@Nauzer When i set `<preference name="CrosswalkAnimatable" value="true" />` in the config.xml my app crashes on start up on android. How can i resolve this? Ever experienced something like this? I'm using cordova-plugin-crosswalk-webview@2.3.0 and with the latest ionic.

**Comment by felixbroehl** [comment]
<preference name="animatableXwalkView" value="true" /> not crashing the app ;)

**Comment by bitjson** [comment]
Crosswalk is no longer maintained, so I'm closing this. Feel free to open a new issue/PR if you'd like to see something else happen.

**Comment by RobbertWolfs** [comment]
@felixbroehl `<preference name="animatableXwalkView" value="true" />` is not crashing the app, but did this fixed the issue?
