### ISSUE TITLE
(Half) white screen 

### ISSUE THREAD

**Issue by sweebee** [bitpay/cordova-plugin-qrscanner#48]
Sometimes i get a white or a half white screen on the First load on my iphone. Going to an other page and back solves it. 

[Imgur](http://i.imgur.com/Dqfbd6X.jpg)

**Comment by dunkan23** [comment]
I had a similar issue in my ionic framework app. Apparently the css that should hide the body background doesn't get applied. I used this to force it to work:

`document.body.style.display = 'none';
$timeout(function() {
    document.body.style.display = 'block';
}, 100);`

Dirty, but functional.

**Comment by bitjson** [comment]
Thanks for sharing @dunkan23. I'm not sure if there's a better way of handling this within the plugin – it really just requires fine-tuning in your app. 

I'm going to close this issue for now, but please let me know if I should reopen.

**Comment by sebhorin** [comment]
I also had some white screen problems I fixed using it in this order:

```
               QRScanner.show(function(argument) {
                    $rootScope.$apply(function(argument) {
                        document.getElementById("app-view").style.display = 'none';
                    });
                });
```
