### ISSUE TITLE
Other types of barcodes?

### ISSUE THREAD

**Issue by MiroHibler** [bitpay/cordova-plugin-qrscanner#52]
Are there plans to broaden the scanning capabilities with, for example UPC, EAN, CODE and other codes?

**Comment by bitjson** [comment]
Hi @MiroHibler – as of now, we have no plans for this plugin to support anything other than QR codes, but that functionality is available in [phonegap-plugin-barcodescanner](https://github.com/phonegap/phonegap-plugin-barcodescanner) if you're interested.

Going to close this for now, but if you decide to maintain a fork adding that functionality, I'd love to link to it from the readme!
