### ISSUE TITLE
How to cancel scanning on ios

### ISSUE THREAD

**Issue by yoprogramo** [bitpay/cordova-plugin-qrscanner#64]
Hello,

I have a cordova project running well on iOS and Android. When someone wants to cancel the scanning, in Android I can do capturing the backbutton, but iOS have not such button/event, so, how can I make the user be able to cancel the scanning?

**Comment by dcousens** [comment]
@yoprogramo add a HTML tappable icon,  say an `X`,  in the corner,  and if that icon is tapped, close the camera.

**Comment by bitjson** [comment]
Yep, @dcousens's solution would work.

The purpose of this plugin is to give you fine-grained control over the camera UX. If you are less concerned about the interface, you might find that [phonegap-plugin-barcodescanner](https://github.com/phonegap/phonegap-plugin-barcodescanner) fits your needs better (few options and a one-size-fits-all interface).

I don't think there's an issue with the repo here, so I'm going to close this issue for now. Please let me know if I should reopen.
