### ISSUE TITLE
Click sound when using the scanner

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/cordova-plugin-qrscanner#69]
When I'm scanning a click sounds appears. And stops when I cancel the scanner.
Device: Microsoft Lumia 640. On test-app

**Comment by nacardin** [comment]
I have resolved the issue by using `GetPreviewFrameAsync` instead of `CapturePhotoToStreamAsync`. `CapturePhotoToStreamAsync` causes a shutter sound on Windows 10. I will make a combined PR which fixes this and other issues.
