### ISSUE TITLE
iOS: Camera video preview layer should not rotate with orientation change

### ISSUE THREAD

**Issue by gitmh** [bitpay/cordova-plugin-qrscanner#7]
When you have a landscape cordova app and start scanning the camera is not rotated correctly. The AVCaptureVideoOrientation should change with rotating the device.

**Comment by bitjson** [comment]
Hey @gitmh, thanks for the report! That's something I've not considered. Does the rotation matter when scanning QR codes? (Does it scan differently?) How do you think the plugin should handle device orientation?

**Comment by gitmh** [comment]
I have a cordova app which is fixed to landscape only. The scanning also works without rotation but it is very annoying to "find" the code if you move left and the preview moves right and vice versa because the video preview is rotated 180° on your screen (up is down and down is up). 

I'm not very familiar with Swift so I tried to fix this by adding something like this:
```
        let app = UIApplication.sharedApplication()
        switch app.statusBarOrientation {
        case .Portrait:
            captureVideoPreviewLayer?.connection.videoOrientation = AVCaptureVideoOrientation.PortraitUpsideDown;
        case .PortraitUpsideDown:
            captureVideoPreviewLayer?.connection.videoOrientation = AVCaptureVideoOrientation.Portrait;
        case .LandscapeLeft:
            captureVideoPreviewLayer?.connection.videoOrientation = AVCaptureVideoOrientation.LandscapeRight;
        case .LandscapeRight:
            captureVideoPreviewLayer?.connection.videoOrientation = AVCaptureVideoOrientation.LandscapeLeft;
        default:
            captureVideoPreviewLayer?.connection.videoOrientation = AVCaptureVideoOrientation.LandscapeRight;
        }
```

I was unable to figure out where to place this, so it will be applied whenever the orientation changes. It may look strange, but if the device is LandscapeRight, the videoOrientation must be set to the opposite direction LandscapeLeft.

I don't know if connection.videoOrientation is the correct spot to change - maybe it is the captureVideoPreviewLayer itself that needs to rotate with the rest of the app?

**Comment by bitjson** [comment]
Hey @gitmh, thanks again for the report. Just wanted to let you know that I'm currently finishing up with the browser implementation (https://github.com/bitpay/cordova-plugin-qrscanner/pull/6), but this is on my radar. I plan to take a swing at this issue once the initial browser implementation is merged.

**Comment by bitjson** [comment]
Still looking at this – I added some device orientation controls to the manual tests to help with testing for this issue: https://github.com/bitpay/cordova-plugin-qrscanner/commit/d9a11cdabbeb004cd9e1d877680ffac6108c592f#diff-2a8a5fef3397df87ab538f028a5c6b50R96

I'm not very familiar with iOS's layout system – I think the best solution is to disable orientation changes on just the video preview layer (such that the camera always stays oriented with the screen as the device is rotated). I've not been able to get a working solution yet – pull requests welcome!

**Comment by dmitrianosov** [comment]
Hi, This is dmitri from upwork.

**Comment by dmitrianosov** [comment]
Hi, This is dmitri from upwork.

**Comment by dmitrianosov** [comment]
Hi, This is dmitri from upwork.

**Comment by dmitrianosov** [comment]
Hi, This is dmitri from upwork.

**Comment by dmitrianosov** [comment]
Hi, This is dmitri from upwork.

**Comment by dmitrianosov** [comment]
Hi, This is dmitri from upwork.

**Comment by gitmh** [comment]
@bitjson I also very unfamiliar with this orientation stuff. The solution I mentioned in the dropbox link with a timer works very well in my app. The problem is that I was unable to register a proper event handler for the orientation change.
