### ISSUE TITLE
Deprecated URL.createObjectURL(stream) is used

### ISSUE THREAD

**Issue by fhbmax** [bitpay/cordova-plugin-qrscanner#72]
Chrome 57 beta logs the following warning when scan() is called:

> URL.createObjectURL(stream) is deprecated! Use elem.srcObject = stream instead!

[Mozilla Devoloper Network:](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL)
> The use of a MediaStream object as an input to this method is in the process of being deprecated.  Discussions are ongoing about whether or not it should be removed outright. As such, you should try to avoid using this method with MediaStreams, and should use HTMLMediaElement.srcObject() instead.

**Comment by bitjson** [comment]
Thanks for opening an issue! This project uses [`webrtc/adapter`](https://github.com/webrtc/adapter) to polyfill functionality properly. We're up to date with the latest version, so I don't think we need to do anything here. If you'd like it to be corrected, you might want to open an issue there. When a new version gets released, we will definitely update to the latest.

I'm going to close this for now, but please let me know if I should reopen. (And if you open an issue at that repo, please post the link here!)
