### ISSUE TITLE
How to make iOS re-render the webview background as transparent

### ISSUE THREAD

**Issue by Ethan9001** [bitpay/cordova-plugin-qrscanner#76]
I have used a lot of ways to set the element transparent, still no effect. But in the debugging time, switch the background when the transparent style will be successful. Said do not understand

**Comment by mljsgto222** [comment]
I fixed that by change the position of a element after QrScanner.show().Test on iOS 10.2 and 10.3.
I think this is because webview does not render elements that are under opaque elements, so you need to trigger reflow to render it, and setting background will only make it redraw the element.

**Comment by fahadpathan** [comment]
How you have changed the position?

**Comment by mljsgto222** [comment]
@fahadpathan The body position is 'fixed' In the Ionic, so I just changed it to 'static' in callback of QrScanner.show().

**Comment by fahadpathan** [comment]
@mljsgto222 I have added background ''transparent' inside QrScanner.show();.

**Comment by mljsgto222** [comment]
@fahadpathan I mean you need to trigger Webview to reflow. I changed the body position, you can also use other ways. But changing background will only trigger the browser to repaint.

**Comment by fahadpathan** [comment]
@mljsgto222 Yes I repainted browser, as we need customer layout for QR Code similar to WhatsApp QR Code scanner.

**Comment by bitjson** [comment]
Hey @fahadpathan and @mljsgto222 – were you able to solve this issue? Making the webview transparent in iOS is somewhat finicky, and depending on your app, you might need to do some adding/removing CSS elements to trigger the view to be redrawn as transparent. You can see https://github.com/bitpay/copay for an example. (Links to the live version in app stores here: https://bitpay.com/wallet)

If you have any ideas for how we can modify this plugin to work better "out-of-the-box", I'd love to take a pull request!
