### ISSUE TITLE
Installation / testing issues

### ISSUE THREAD

**Issue by h-evers** [bitpay/cordova-plugin-qrscanner#79]
I had some issues with the installation for testing the plugin - just in case i'm not the only one.

1. gulp dependency is not noted anywhere (i use grunt), so i had to install.
Of course you can see from gulpfile.js and reading the output, but it may be helpful to note that.

2. webpack dependency seems to be tricky, i had to downgrade to exactly "2.1.0-beta.22".
Not sure why exactly it did not work for me, but i'm not the only one: https://github.com/roots/sage/issues/1720

Thank for maintaining this awesome plugin.

**Comment by gabrielbazan7** [comment]
Yes, you have to downgrade to exactly "2.1.0-beta.22". I send a PR fixing that issue.

https://github.com/bitpay/cordova-plugin-qrscanner/pull/78

**Comment by bitjson** [comment]
1. @h-evers – did you see the [contributing & testing info here](https://github.com/bitpay/cordova-plugin-qrscanner#contributing--testing)? When you `npm install`, gulp should be installed properly. Did that not work?

2. Thanks for the note – we should try to get Webpack updated to the latest version, 2.1.0 was quite a while ago. Tracking in #78.

**Comment by bitjson** [comment]
I'm merging this into #78 for now, but @h-evers please let me know if you're seeing something unexpected/undocumented for item (1.) above!

**Comment by h-evers** [comment]
I now had the time to do a fresh installation and tried again. I missed the needed
> npm install gulp-cli -g
i did last time after some peeking around. Thats obvious for people working with gulp - but not for grunt users (although i did similar for grunt a long time ago then).

**Comment by bitjson** [comment]
Hey @h-evers – you shouldn't ever need to install or run gulp separately for this repo, gulp is only used internally by the npm scripts. Hope that clears things up!

**Comment by h-evers** [comment]
Does not work here (OS X 10.11.6) - i don't know exactly why. Fresh install
> npm install
> npm run gen-tests

fails with

"Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema. configuration.output.path: The provided value './src/browser' is not an absolute path!"

Somehow i managed to get over this error, but i cannot say which step helped. Maybe it had nothing to do with the mentioned gulp-cli.
