### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by mattsilv** [bitpay/cordova-plugin-qrscanner#8]
com.google.android.gms.vision.barcode seems to have classes to support barcode scanning using Google Play services.  Is it possible to extend that into this plugin for supporting barcodes scanning on Anrdoid?

http://android-developers.blogspot.se/2015/08/barcode-detection-in-google-play.html

**Comment by bitjson** [comment]
Definitely possible! I plan to develop Android and Windows platforms for this plugin, but I haven't had the time yet. I'd love to accept a pull request if you're interested in working on it!

**Comment by Giriton** [comment]
There is a plugin that already does live camera preview on android that is rendered over the cordova app. We use that plugin and I believe the hardest part of Android support is already done there:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview

The rest to implement is just to use ZXing or com.google.android.gms.vision.barcode to look for QR in camera object and make a callbacks once it was found.

Note: if you use Crosswalk on Cordova with Android, you need to add some parameters to your config.xml to make this plugin work, see my comment here: https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/3#issuecomment-229025649

**Comment by bitjson** [comment]
Work on this is starting here: https://github.com/bitpay/cordova-plugin-qrscanner/pull/9

**Comment by bitjson** [comment]
This has now shipped: https://github.com/bitpay/cordova-plugin-qrscanner/pull/16

**Comment by burtontanner** [comment]
how hard would it be to get android to support data martix codes?
