### ISSUE TITLE
QRScanner.scan's callback should receive an error if the user cancels the scan

### ISSUE THREAD

**Issue by n00dl3** [bitpay/cordova-plugin-qrscanner#80]
If you cancel the scan, there is no way to know that the user has canceled the operation... the scan callback should be called with an error parameter like `ABORTED_BY_USER`. 

It's very painful when working with rxJS, for example.

BTW: thank you for this plugin, it is great.

**Comment by bitjson** [comment]
Hey @n00dl3 – thanks!

I'm not sure if I understand entirely – the [`SCAN_CANCELED` error](https://github.com/bitpay/cordova-plugin-qrscanner#possible-error-types) is returned to the `scan` callback if the scan is canceled – is that what you're looking for?

Is it possible for an end user to cancel a scan without [`cancelScan`](https://github.com/bitpay/cordova-plugin-qrscanner#scan)? The plugin doesn't provide any type of native interface, so the only way for the scan to be canceled should be via that method. (Or by closing the app.)

**Comment by n00dl3** [comment]
Yeah, I was looking for the `SCAN_CANCELLED` error, it was right there and I didn't see it. It seems I didn't receive it when the scan is cancelled. Nevermind, I'll investigate and reopen if that's really the case.
