### ISSUE TITLE
Can I use without cordova?

### ISSUE THREAD

**Issue by Naki21** [bitpay/cordova-plugin-qrscanner#83]
I am developing a web app and I hope to implement a qr scanner. I came across this library and it looks very robust. I installed it via npm and tried to require('cordova-plugin-qrscanner') as I have done with my other npm modules. I am kind of confused as to how this library can be integrated into my App or if its even possible. I am not using any front end frameworks. Am I completely missing something here? Any clarification would be great. Thanks!

**Comment by bitjson** [comment]
Yes, you should be able to simply include the minified library on the page, and the proper methods will be added to the window object. It's distributed as in [UMD](https://github.com/umdjs/umd) format, so it should also work as expected with your CommonJS project.

Be sure to check out the [Browser readme section](https://github.com/bitpay/cordova-plugin-qrscanner#browser) platform for specific notes.

**Comment by bitjson** [comment]
On another note – if you're trying to require it, your CommonJS loader may be looking inside `package.json` for a `main` field, which I'm just realizing isn't defined. Looking into that now.

**Comment by bitjson** [comment]
Ok – I just added the property in this commit: https://github.com/bitpay/cordova-plugin-qrscanner/commit/955e375c7d9766a106a6b6f65c0f204fe430fc20

It should be included in the next release of `cordova-plugin-qrscanner`. Until then, you can get it working by adding the property to the `package.json` file in `node_modules/cordova-plugin-qrscanner` like in the commit:

```json
...
"main": "dist/cordova-plugin-qrscanner-lib.min.js",
...
```

Please let me know if that solves the issue!

**Comment by Naki21** [comment]
You beautiful, beautiful unicorn man. Seems to have worked like a charm This is going to work wonders in my app. This is by far the most robust and well maintained qr scanning library I have found. I appreciate the help and speedy response

**Comment by bitjson** [comment]
Glad to hear it, thanks for opening the issue!
