### ISSUE TITLE
Install failed because of file not found

### ISSUE THREAD

**Issue by nathan8899** [bitpay/cordova-plugin-qrscanner#86]
failed to install the plug in due to the following error.  

ENOENT, no such file or directory 'C:\Cordova\TestingProject\plugins\cordova-plugin-qrscanner\www\www.min.js'

**Comment by Kradre** [comment]
Same here, tried to install directly from git repo and this error happend.
It because of dep in plugin.xml :

` <js-module src="www/www.min.js" name="QRScanner">
    <clobbers target="QRScanner" />
  </js-module>`


Any ideas where to link this?

**Comment by bitjson** [comment]
You'll need to install from Cordova/NPM, the github repo doesn't have the built javascript files committed.

If you absolutely have to install from GitHub, you'll need to build the files yourself. You can `npm run build` inside `node_modules/cordova-plugin-qrscanner`.
