### ISSUE TITLE
Cant get camera preview to work

### ISSUE THREAD

**Issue by vajura** [bitpay/cordova-plugin-qrscanner#91]
http://imgur.com/a/jrnpc what i currently get.

I am calling QRScanner.prepare and it returns authorized but after calling QRScanner.show() i only get what you see in the picture.

**Comment by bitjson** [comment]
It looks like you're trying to use the webRTC version on Android. Did you install the Cordova plugin, or are you importing the javascript library? See [Get Started](https://github.com/bitpay/cordova-plugin-qrscanner#get-started) for details.

If you install the Cordova plugin, you won't need to import any JavaScript.

![4q3gt9m](https://cloud.githubusercontent.com/assets/904007/25490212/1ffa9c96-2b3a-11e7-8c4f-765d88958461.png)

(Copying into Github issues for posterity. ^)
