### ISSUE TITLE
SecurityError shown in the console on prepare, scan, ...

### ISSUE THREAD

**Issue by sasos90** [bitpay/cordova-plugin-qrscanner#94]
Hi!

I am facing an issue when I want to use the QRScanner. I get some error which I can not debug, so I am becoming desperate.
The QRScanner object is defined and some methods work properly (cancelScan, etc.), but when it comes to the camera usage or something, when I use scan, prepare etc., then I get some error in the console like: "SecurityError" and that's all. Somewhere I also found the error in that form:
```
ERROR Error: Uncaught (in promise): Error: SecurityError
Error: SecurityError
 at viewWrappedDebugError (ms-appx://app.namespace/www/vendor.bundle.js:8958:9) [angular]
```

After few seconds (around 20) I also get that in the console:
```
HTML7007: One or more blob URLs were revoked by closing the blob for which they were created. These URLs will no longer resolve as the data backing the URL has been freed.
www
```

So I can not run the scanner on the Windows phone 8.1 device.

Does anyone have a clue what is happening there?

Thanks in advance!

**Comment by bitjson** [comment]
Fixed in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) 🚀
