### ISSUE TITLE
no camera preview on ios 10.3

### ISSUE THREAD

**Issue by zweipro-kleff** [bitpay/cordova-plugin-qrscanner#95]
I'm using the qrscanner with ionic 3 and I can't get rid of the white background covering the camera preview on ios 10.3. 
getStatus() shows this: 
```
authorized: true
canChangeCamera: true
canEnableLight: true
canOpenSettings: true
currentCamera: 0
denied: false
lightEnabled: false
prepared: true
previewing: true
restricted: false
scanning: true
showing: true
```
Even without the preview the scanner actually scans. On android the preview is working fine. Both ios and android versions tested on real devices. One thing that's pretty strange is that if i connect the iphone to safari on my mac and change anything there, for example disabling a random padding or whatever, the white background disappears and the camera preview is shown.

any help solving this would be appreciated :)

**Comment by fahadpathan** [comment]
try adding css class as background transparent to to HTML, BODY and wrapper if any exclusively in qrscanner.show().

**Comment by stefanhuber** [comment]
I had the same problem. I couldn't find a solution with css, however switching to WKWebView worked.

**Comment by zweipro-kleff** [comment]
Switching to WKWebView worked!

Thanks for the help!

**Comment by RuiEEE** [comment]
How did you guys manage to change to WKWebView ?

**Comment by gabrielbazan7** [comment]
Try adding this to your sass file : 

```
html , body, .back-trasnparente, ion-app, .nav-decor {
  background: none transparent !important;
}
```
