### ISSUE TITLE
trouble loading plugin into project.

### ISSUE THREAD

**Issue by synergy1337** [bitpay/cordova-plugin-qrscanner#98]
Hi, 

im trying to import/use this plugin after i install it to my meteor (Angular 2) project:

I did both:
npm install --save cordova-plugin-qrscanner
and
meteor add cordova:cordova-plugin-qrscanner@2.5.0 

then in my component.ts file i have the function below:
 
scanStuff() {

QRScanner.scan(displayContents);

function displayContents(err, text){
if(err){
// an error occurred, or the scan was canceled (error code 6) 
} else {

alert(text);
}
}

QRScanner.show();

}

in my html file i have the following:

 `<button (click)="this.scanStuff()"> Scan</button>`

--

When i press the button "Scan" after i load my app in android nothing happens.

Do i have to import the plugin somehow? if so where and in what files?

any help is greatly appreciated!

extra info:
i'm using this boilerplate: https://github.com/Urigo/angular2-meteor-base  -
a fully updated meteor version, and then i add the android platform to my project.

**Comment by bitjson** [comment]
Fixed in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) 🚀
