### ISSUE TITLE
Inverted QR-Codes

### ISSUE THREAD

**Issue by zweipro-kleff** [bitpay/cordova-plugin-qrscanner#99]
Is it possible to scan inverted qr-codes with this plugin? (white code on dark background)
If not, where would i have to look to add this functionality?

Thanks in advance!

**Comment by Prenoult** [comment]
You probably tested by your own, but I can guarantee now that this plugin can scan inverted QR codes ! 👍

**Comment by zweipro-kleff** [comment]
Yeah, can confirm. I can scan now most of my inverted qr codes. Just one where the contrast between code and background seems to be too low doesn't work. But i guess that's ok.
No idea though why it didn't work when i first tested it.
